# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml requirements.txt README.md ./
COPY src/ src/

# Install Python dependencies and project
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir .

# Default command
ENV PYTHONUNBUFFERED=1
CMD ["csv-editor", "--transport", "stdio"]
